= geochemxl

This is a Python package that can be used either on the command line or within other programs as a library that converts Geochemistry Excel Workbooks into RDF data.

This module requires Workbooks to be structured using GeochemXL templates.

This package is used by the https://geochem.dev.kurrawong.ai[Geochemistry Data Portal]. Go there to use this without installing anything!

== Code Repository

This software's code repository is online at https://github.com/Kurrawong/geochemxl

== Template versions

This software works with GeochemXL Excel template versions 3+. All supported templates are stored in the `templates/` directory of this software's code repository.

Examples of

== Use

=== Online Use

Use this online at https://geochem.dev.kurrawong.ai[Geochemistry Data Portal].

=== Basic Use

The command line command to run this program against `Workbook-X.xlsx` and to produce RDF file named `x.ttl` is:

[source]
----
~$ python -m geochemxl -o x.ttl Workbook-X.xlsx
----

Run this command from the directory above the `geochemxl` package (the geochemxl directory containing `convert.py`).

Generally:

[source]
----
~$ python -W ignore -m geochemxl -o {PATH_TO_OUTPUT_FILE} {PATH_TO_EXCEL_FILE}
----

`-W ignore` is used to ignore a series of low-level warnings that are not necessary to see.

`-m geochemxl` means 'run the Python module geochemxl'

`-o` tells the program where to write the output file to. If no `-o` is supplied then output will be written to screen


To use the test workbook for version 3.0 in the `tests/data/3.0/ directory, run this command:

[source]
----
~$ python -W ignore -m geochemxl -o tests/data/3.0/geochemxl.ttl tests/data/3.0/GeochemXL-3.0-integration.xlsx
----

You should see a result printed out like this:

[source]
----
Processing workbook tests/data/3.0/GeochemXL-3.0-integration.xlsx
----

and a resulting RDF data file `tests/data/3.0/geochemxl.ttl`.

=== Command Line Argument details

You can print out all the command line argument options by asking for 'help' like this:

[source]
----
~$ python -m geochemxl -h
----

...and you will get:

[source]
----
usage: geoexcelrdf [-h] [-i] [-o OUTPUTFILE] [-u] [file_to_convert]

positional arguments:
  file_to_convert       The Excel file to convert to a SKOS vocabulary in RDF or an RDF file to convert to an Excel file (default: None)

options:
  -h, --help            show this help message and exit
  -i, --info            The version and other info of this instance of Geochem Excel Converter (default: False)
  -o OUTPUTFILE, --outputfile OUTPUTFILE
                        An optionally-provided output file path. If not provided, output is to standard out (default: None)
  -u, --update_workbook
                        Update a given Excel Workbook's vocabularies (default: False)
----

== Testing

See the test data file `tests/data/3.0/geochemxl.ttl` produced from the workbook `tests/data/3.0/GeochemXL-3.0-integration.ttl`.

This code uses https://pypi.org/project/pytest/[pytest] to run its test suite. After installing pytest, you can run the entire suite from the command line, from within the directory about the geochemxl module like this:

[source]
----
~$ pytest
----

That's it! You might like to hide annoying warnings:

[source]
----
~$ pytest -W ignore
----

You should see something like this:

[source]
----
===================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.11.0b5, pytest-7.4.3, pluggy-1.3.0
rootdir: /Users/nick/Work/gsq/geochemxl
collected 62 items

tests/test_conversion.py .............................................................                                                                                                  [ 98%]
tests/test_utils.py .                                                                                                                                                                   [100%]
----

Most of the tests are for conversion methods in the file `geochemxl/conversion.py` and they are in the file `tests/test_conversion.py`. There are a few tests for supporting untilities in `geochemxl/utils.py` in `tests/test_utils.py` too.

=== Test data files

Excel workbooks containing single worksheets with static data for testing are stored in the `tests/data/` directory within this directory. In there too is a complete Workbook with information on every sheet that is used for integration tests within `tests/test_conversion.py`.

== Installation

This package is installed using the https://python-poetry.org/[Poetry] dependency manager.

All the supporting packages needed are given in the `pyproject.toml` file and can be installed into a Python virtual environment like this:

[source]
----
~$ poetry init
~$ poetry update
----

== Supporting vocabularies

Use of GeochemXL requires the vocabularies used to make the VALIDATION_DICTIONARY, UNITS_OF_MEASURE, LITH_DICTIONARY & MIN_DICTIONARY worksheets to be present. these vocabularies are managed by GSQ's https://gsq-prez.dev.kurrawong.ai/v#geochem-vocabs[Vocabulary Server]. A compounded copy of each template version's vocabs called `combined-concepts` is contained in the `tests/data/` directory and it's used within the testing functions.

== Tracking Issues

The issue tracker for this software is online at https://github.com/Kurrawong/geochemxl/issues. Please log all bugs/issues/feature requests there.

== License & Rights

This software was developed by https://kurrawong.ai[KurrawongAI] for the https://www.business.qld.gov.au/industries/mining-energy-water/resources/geoscience-information/gsq[Geological Survey of Queensland]. It is available for free use under terms of the https://creativecommons.org/licenses/by/4.0/[Creative Commons BY 4.0] license, a copy of the deed of which is contained in the file LICENSE in this software's source repository.

This software is all &copy; The State of Queensland, 2023

== Contacts

For general use, please contact:

*Geoscience Information Team* +
Geological Survey of Queensland +
Department of Resources +
Brisbane, QLD, Australia +
geological_info@resources.qld.gov.au

For all technical matters, software development etc please contact the authors:

*KurrawongAI* + 
Brisbane Queensland +
https://kurrawong.ai +
info@kurrawong.ai 